"""Signal definitions for the strategy layer."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from alpha_quat.core import Price, SignalDirection, Urgency


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    ts_code: str
    direction: SignalDirection
    strength: float = 1.0
    urgency: Urgency = Urgency.NORMAL
    limit_price: Price | None = None
    stop_price: Price | None = None
    timestamp: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_long(self) -> bool:
        """Check if this is a long signal."""
        return self.direction == SignalDirection.LONG

    @property
    def is_short(self) -> bool:
        """Check if this is a short signal."""
        return self.direction == SignalDirection.SHORT

    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal."""
        return self.direction in (
            SignalDirection.EXIT_LONG,
            SignalDirection.EXIT_SHORT,
            SignalDirection.FLAT,
        )

    @property
    def is_exit_long(self) -> bool:
        """Check if this is an exit long signal."""
        return self.direction == SignalDirection.EXIT_LONG

    @property
    def is_exit_short(self) -> bool:
        """Check if this is an exit short signal."""
        return self.direction == SignalDirection.EXIT_SHORT

    @property
    def is_flat(self) -> bool:
        """Check if this is a flat signal (exit all positions)."""
        return self.direction == SignalDirection.FLAT
